### ISSUE TITLE
Internal error when using pylint-django 0.11.1 with InheritanceManager

### ISSUE THREAD

**Issue by nirsalon** [PyCQA/pylint-django#164]
Repro steps:
Run pylint on the following file
```from django.db import models
from model_utils.managers import InheritanceManager
class Unit(models.Model):
    sim = models.CharField(max_length=64, null=True, blank=True)
    objects = InheritanceManager()
```
and get the following error

> internal error with sending report for module ['C:\\work\\test.py']
> 'SoftDeletableManager'
> Using config file C:\work\.pylintrc

using pylint 1.9.2 and pylint-django 0.11.1
it works well on 0.11

**Comment by atodorov** [comment]
Can you post a traceback  and also your pylintrc file ?

**Comment by nirsalon** [comment]
i've stripped pylintrc to the following:
```
[MASTER]
load-plugins=pylint_django
```
and this is the traceback
```
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\work\p\Scripts\pylint.exe\__main__.py", line 9, in <module>
  File "c:\work\p\lib\site-packages\pylint\__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "c:\work\p\lib\site-packages\pylint\lint.py", line 1347, in __init__
    linter.check(args)
  File "c:\work\p\lib\site-packages\pylint\lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "c:\work\p\lib\site-packages\pylint\lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "c:\work\p\lib\site-packages\pylint\lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "c:\work\p\lib\site-packages\pylint\utils.py", line 1014, in walk
    self.walk(child)
  File "c:\work\p\lib\site-packages\pylint\utils.py", line 1011, in walk
    cb(astroid)
  File "c:\work\p\lib\site-packages\pylint\checkers\variables.py", line 1262, in visit_importfrom
    module = self._check_module_attrs(node, module, name_parts[1:])
  File "c:\work\p\lib\site-packages\pylint\checkers\variables.py", line 1332, in _check_module_attrs
    module = next(module.getattr(name)[0].infer())
  File "c:\work\p\lib\site-packages\astroid\scoped_nodes.py", line 489, in getattr
    result = [self.import_module(name, relative_only=True)]
  File "c:\work\p\lib\site-packages\astroid\scoped_nodes.py", line 593, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "c:\work\p\lib\site-packages\astroid\manager.py", line 154, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "c:\work\p\lib\site-packages\astroid\manager.py", line 80, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "c:\work\p\lib\site-packages\astroid\builder.py", line 153, in file_build
    return self._post_build(module, encoding)
  File "c:\work\p\lib\site-packages\astroid\builder.py", line 177, in _post_build
    module = self._manager.visit_transforms(module)
  File "c:\work\p\lib\site-packages\astroid\manager.py", line 62, in visit_transforms
    return self._transform.visit(node)
  File "c:\work\p\lib\site-packages\astroid\transforms.py", line 84, in visit
    return self._transform(module)
  File "c:\work\p\lib\site-packages\astroid\transforms.py", line 36, in _transform
    ret = transform_func(node)
  File "c:\work\p\lib\site-packages\pylint_django\transforms\__init__.py", line 35, in set_fake_locals
    module.locals[class_name].extend(fake.locals[class_name])
KeyError: 'SoftDeletableManager'
```

**Comment by atodorov** [comment]
what is your model_utils version?  Is it < 2.6 by any chance ?

**Comment by atodorov** [comment]
FYI: I can't reproduce with the code snippet that you posted and I have django-model-utils==3.1.2 which is the latest version. The traceback suggests that SoftDeletableManager class is not yet defined!

**Comment by nirsalon** [comment]
The for the details. I've updated to django-model-utils==2.6.1 and it works now.
