### ISSUE TITLE
'NewStyleConflictChecker' has no attribute 'visit_classdef'

### ISSUE THREAD

**Issue by makr11** [PyCQA/pylint-django#203]
Full traceback

Traceback (most recent call last):
  File "c:\users\marin\appdata\local\programs\python\python37-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\marin\appdata\local\programs\python\python37-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Marin\dev\spartacus_django_react\backend\Scripts\pylint.exe\__main__.py", line 9, in <module>
  File "c:\users\marin\dev\spartacus_django_react\backend\lib\site-packages\pylint\__init__.py", line 20, in run_pylintackages\pylint\__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])                                               ackages\pylint\lint.py", line 1521, in __init__
  File "c:\users\marin\dev\spartacus_django_react\backend\lib\site-packages\pylint\lint.py", line 1521, in __init__                     ackages\pylint\lint.py", line 651, in load_plugin_modules
    linter.load_plugin_modules(self._plugins)
  File "c:\users\marin\dev\spartacus_django_react\backend\lib\site-packages\pylint_django\plugin.py", line 30, in registerackages\pylint\lint.py", line 651, in load_plugin_modules
    module.register(self)  File "c:\users\marin\dev\spartacus_django_react\backend\lib\site-packages\pylint_django\plugin.py", line 30, in register    apply_augmentations(linter)
  File "c:\users\marin\dev\spartacus_django_react\backend\lib\site-packages\pylint_django\augmentations\__init__.py", line 790, in apply_augmentations    suppress_message(linter, NewStyleConflictChecker.visit_classdef, 'old-style-class', is_model_meta_subclass)AttributeError: type object 'NewStyleConflictChecker' has no attribute 'visit_classdef'

Pip freeze 

astroid==2.1.0
colorama==0.4.1
Django==2.1.3
django-cors-headers==2.4.0
django-rest-framework==0.1.0
djangorestframework==3.9.0
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
pylint==2.2.0
pylint-django==2.0.2
pylint-plugin-utils==0.4
pytz==2018.7
six==1.11.0
typed-ast==1.1.0
wrapt==1.10.11

**Comment by carlio** [comment]
Should be fixed in the 2.0.4 version that was just released
