### ISSUE TITLE
v0.8.1: AttributeError: 'module' object has no attribute 'VERSION'

### ISSUE THREAD

**Issue by sphuber** [PyCQA/pylint-django#235]
I am running into this exception with `pylint-django==0.8.1` and `django==1.11.20`.
The stack trace is as follows:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/prospector", line 10, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/prospector/run.py", line 173, in main
    prospector.execute()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/prospector/run.py", line 53, in execute
    for tool in self.config.get_tools(found_files):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/prospector/config/__init__.py", line 41, in get_tools
    config_result = tool.configure(self, found_files)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 182, in configure
    config_messages += self._pylintrc_configure(pylintrc, linter)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 100, in _pylintrc_configure
    are_plugins_loaded = linter.config_from_file(pylintrc)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/prospector/tools/pylint/linter.py", line 27, in config_from_file
    self.load_plugin_modules(plugins)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pylint/lint.py", line 500, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/astroid/modutils.py", line 190, in load_module_from_name
    return load_module_from_modpath(dotted_name.split('.'), path, use_sys)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/astroid/modutils.py", line 233, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pylint_django/__init__.py", line 7, in <module>
    from pylint_django import plugin
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pylint_django/plugin.py", line 3, in <module>
    from pylint_django.augmentations import apply_augmentations
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pylint_django/augmentations/__init__.py", line 9, in <module>
    from pylint_django.compat import ClassDef, ImportFrom, Attribute, django_version
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pylint_django/compat.py", line 22, in <module>
    django_version = django.VERSION
AttributeError: 'module' object has no attribute 'VERSION'
```
This is happening on my Travis environment with the following packages:
```
Flask-1.0.2
Flask-Cache-0.13.1
Flask-Cors-3.0.7
Flask-HTTPAuth-3.2.4
Flask-RESTful-0.3.7
Flask-SQLAlchemy-2.3.2
Jinja2-2.10.1
Mako-1.0.12
MarkupSafe-1.1.1
PyCifRW-4.2.1
PyMySQL-0.9.3
PyYAML-3.13
Pygments-2.3.1
SQLAlchemy-1.3.3
SQLAlchemy-Utils-0.33.11
Send2Trash-1.5.0
Sphinx-1.8.4
Tempita-0.5.2
Werkzeug-0.15.4
aiida-core-1.0.0b3
alabaster-0.7.12
aldjemy-0.9.1
alembic-1.0.7
aniso8601-7.0.0
argparse-1.4.0
ase-3.17.0
aspy.yaml-1.3.0
astroid-1.6.6
atomicwrites-1.3.0
attrs-19.1.0
babel-2.7.0
backports-abc-0.5
backports.functools-lru-cache-1.5
backports.shutil-get-terminal-size-1.0.0
backports.tempfile-1.0
backports.weakref-1.0.post1
bcrypt-3.1.6
bleach-3.1.0
blessings-1.7
bpython-0.17.1
cfgv-2.0.0
circus-0.15.0
click-7.0
click-completion-0.5.1
click-config-file-0.5.0
click-spinner-0.1.8
codecov-2.0.15
configobj-5.0.6
configparser-3.7.4
contextlib2-0.5.5
coverage-4.5.2
curtsies-0.3.0
cycler-0.10.0
decorator-4.4.0
defusedxml-0.6.0
django-1.11.20
docutils-0.14
dodgy-0.1.9
entrypoints-0.3
ete3-3.1.1
flask-marshmallow-0.9.0
frozendict-1.2
functools32-3.2.3.post2
furl-2.0.0
future-0.17.1
futures-3.2.0
greenlet-0.4.15
identify-1.4.4
imagesize-1.1.0
importlib-metadata-0.18
importlib-resources-1.0.2
ipykernel-4.10.0
ipython-5.8.0
ipython-genutils-0.2.0
ipywidgets-7.4.2
isort-4.3.20
itsdangerous-1.1.0
jsonschema-3.0.1
jupyter-1.0.0
jupyter-client-5.2.4
jupyter-console-5.2.0
jupyter-core-4.4.0
kiwipy-0.5.1
kiwisolver-1.1.0
lazy-object-proxy-1.4.1
linecache2-1.0.0
marshmallow-2.19.2
marshmallow-sqlalchemy-0.16.0
matplotlib-2.2.4
mccabe-0.6.1
mistune-0.8.4
monty-2.0.4
more-itertools-5.0.0
mpmath-1.1.0
nbconvert-5.5.0
nbformat-4.4.0
networkx-2.2
nodeenv-1.3.3
notebook-5.7.8
numpy-1.16.1
orderedmultidict-1.0
packaging-19.0
palettable-3.1.1
pandas-0.24.2
pandocfilters-1.4.2
paramiko-2.4.2
passlib-1.7.1
pathlib2-2.3.3
pep8-naming-0.4.1
pexpect-4.7.0
pg8000-1.12.5
pgtest-1.2.0
pickleshare-0.7.5
pika-1.0.0
pluggy-0.12.0
plumpy-0.14.0
pre-commit-1.14.4
prometheus-client-0.7.0
prompt-toolkit-1.0.16
prospector-1.1.6.4
psutil-5.5.1
psycopg2-binary-2.8
ptyprocess-0.6.0
pyasn1-0.4.2
pyblake2-1.1.2
pycodestyle-2.4.0
pydispatcher-2.0.5
pydocstyle-3.0.0
pyflakes-1.6.0
pylint-1.9.4
pylint-celery-0.3
pylint-django-0.8.1
pylint-flask-0.6
pylint-plugin-utils-0.5
pymatgen-2018.12.12
pynacl-1.3.0
pyparsing-2.3.1
pyrsistent-0.15.2
pytest-4.3.0
pytest-cov-2.6.1
python-dateutil-2.8.0
python-editor-1.0.4
python-gssapi-0.6.4
python-memcached-1.59
pytz-2018.9
pyzmq-16.0.4
qe-tools-1.1.2
qtconsole-4.5.1
reentry-1.3.1
requirements-detector-0.6
ruamel.ordereddict-0.4.13
ruamel.yaml-0.15.97
scandir-1.10.0
scipy-1.2.2
seekpath-1.8.4
setoptconf-0.2.0
shellingham-1.3.1
shortuuid-0.5.0
simplegeneric-0.8.1
simplejson-3.16.0
singledispatch-3.4.0.3
snowballstemmer-1.2.1
spglib-1.12.2.post0
sphinx-rtd-theme-0.4.3
sphinxcontrib-contentui-0.2.2
sphinxcontrib-websupport-1.1.2
sqlalchemy-diff-0.1.3
sqlalchemy-migrate-0.12.0
sqlparse-0.3.0
subprocess32-3.5.4
sympy-1.4
tabulate-0.8.3
terminado-0.8.2
testpath-0.4.2
toml-0.10.0
topika-0.2.0
tornado-4.5.3
traceback2-1.4.0
traitlets-4.3.2
typing-3.6.6
tzlocal-1.5.1
unittest2-1.1.0
uritools-2.2.0
virtualenv-16.6.0
wcwidth-0.1.7
webencodings-0.5.1
widgetsnbextension-3.4.2
wrapt-1.11.1
yapf-0.26.0
zipp-0.5.1
```

**Comment by atodorov** [comment]
0.8.1 is a Py2 version which we don't support anymore. Move to the latest version.
