### ISSUE TITLE
astroid.exceptions.AstroidImportError: Failed to import module

### ISSUE THREAD

**Issue by adongy** [PyCQA/pylint-django#241]
Hi,

I believe this is related to #232 but not sure.

pylint_django==2.0.11

```
pylint --version
pylint 2.3.1
astroid 2.2.5
Python 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)]
```

I'm trying to lint:

```
app/
  models/
    __init__.py
```

(simplified, the real code has multiple files inside models/)

with `__init__.py`:

```
from django.db import models

class A(models.Model):
    content_type = models.ForeignKey(
        to="contenttypes.ContentType", on_delete=models.CASCADE
    )
```

I get the following stacktrace:

```
Traceback (most recent call last):
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/astroid/__init__.py", line 91, in _inference_tip_cached
    return iter(_cache[func, node])
KeyError: (<function infer_key_classes at 0x1071a97b8>, <Call l.5 at 0x107b2eeb8>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adongy/work/pylintbug/env/bin/pylint", line 10, in <module>
    sys.exit(run_pylint())
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint/lint.py", line 1628, in __init__
    linter.check(args)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint/lint.py", line 943, in check
    self._do_check(files_or_modules)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint/lint.py", line 1075, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint/lint.py", line 1158, in check_astroid_module
    walker.walk(ast_node)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint/utils.py", line 1303, in walk
    self.walk(child)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint/utils.py", line 1300, in walk
    cb(astroid)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 148, in do_suppress
    chain()
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 56, in chain
    old_method(node)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 148, in do_suppress
    chain()
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 56, in chain
    old_method(node)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 148, in do_suppress
    chain()
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 56, in chain
    old_method(node)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 148, in do_suppress
    chain()
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 56, in chain
    old_method(node)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint/checkers/classes.py", line 729, in visit_classdef
    self._check_bases_classes(node)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint/checkers/classes.py", line 1444, in _check_bases_classes
    unimplemented_abstract_methods(node, is_abstract).items(),
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint/checkers/utils.py", line 782, in unimplemented_abstract_methods
    infered = safe_infer(obj)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint/checkers/utils.py", line 1066, in safe_infer
    value = next(inferit)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/astroid/decorators.py", line 131, in raise_if_nothing_inferred
    yield next(generator)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/astroid/decorators.py", line 95, in wrapped
    res = next(generator)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/astroid/bases.py", line 137, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/astroid/node_classes.py", line 348, in infer
    return self._explicit_inference(self, context, **kwargs)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/astroid/__init__.py", line 93, in _inference_tip_cached
    result = func(*args, **kwargs)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/pylint_django/transforms/foreignkey.py", line 96, in infer_key_classes
    MANAGER.ast_from_module_name(module_name)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/astroid/manager.py", line 178, in ast_from_module_name
    raise e
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/astroid/manager.py", line 129, in ast_from_module_name
    found_spec = self.file_from_module_name(modname, context_file)
  File "/Users/adongy/work/pylintbug/env/lib/python3.7/site-packages/astroid/manager.py", line 222, in file_from_module_name
    raise value
astroid.exceptions.AstroidImportError: Failed to import module contenttypes.models with error:
No module named contenttypes.models.
```

I believe it's trying to treat the app name as an importable module name but that seems incorrect ? (eg contenttypes is django.contrib.contenttypes)

Thanks,

**Comment by atodorov** [comment]
I will close this as known issue as described in #242. The problem in this particular case is that the AST parser is looking for `contenttypes.models.ContentType` which of course doesn't exist. I don't see a reason why you would not reference this model by class instead of string.

See also #243 for proposal how to start making the overall situation better.

**Comment by fkromer** [comment]
@atodorov How can I fix this issue when it pops up w.r.t. `models.OneToOne` instead of `models.ForeignKey`?

**Comment by fkromer** [comment]
@atodorov `models.ForeignKey` and `models.OneToOne` behave equally w.r.t. lazy relationship reference https://docs.djangoproject.com/en/3.0/ref/models/fields/#foreignkey . When using only one Django app there is the workaround of using the `model` syntax instead of the `APP-NAME.model` syntax. However in case you use several Django apps you have to use the `APP-NAME.model` syntax. In this case the issue cannot be solved and there is no workaround I know about. I'd suggest to reopen the issue or open a new one. For more details refer to https://stackoverflow.com/a/60996194/5308983 .
