### ISSUE TITLE
Bug as of `2.4.0` `No module named django`

### ISSUE THREAD

**Issue by ehontoria** [PyCQA/pylint-django#327]
# Description
As of version `2.4.0` the following configuration errors out with ```ModuleNotFoundError: No module named 'django'```.

_This use case works without an error (there is still F5101) in `2.3.0`._

## Configuration
`pylint` release: pylint-2.7.4
`pylint-django` version: 2.4.0

`.pre-commit-config.yaml`:
```
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.4
    hooks:
        - id: pylint
          args: ["--rcfile", ".pylintrc"]
          additional_dependencies:
              - pylint_django==2.4.0
```

`.pylintrc`:
```
[MASTER]
load-plugins=pylint_django
```

# Error
## Expected Output
```
(venv3) emily.hontoria@EmilyHontoriaMBP app % pre-commit run pylint --files setup.py
[INFO] Initializing environment for https://github.com/PyCQA/pylint:pylint_django==2.3.0.
[INFO] Installing environment for https://github.com/PyCQA/pylint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
pylint...................................................................Failed
- hook id: pylint
- exit code: 21

************* Module setup
setup.py:23:0: C0301: Line too long (116/100) (line-too-long)
setup.py:24:0: C0301: Line too long (109/100) (line-too-long)
setup.py:51:0: C0301: Line too long (151/100) (line-too-long)
setup.py:93:0: C0301: Line too long (117/100) (line-too-long)
setup.py:104:0: C0301: Line too long (113/100) (line-too-long)
setup.py:113:0: C0301: Line too long (102/100) (line-too-long)
setup.py:140:0: C0301: Line too long (114/100) (line-too-long)
setup.py:1:0: C0114: Missing module docstring (missing-module-docstring)
setup.py:12:0: C0116: Missing function or method docstring (missing-function-docstring)
setup.py:174:0: C0115: Missing class docstring (missing-class-docstring)
setup.py:183:8: W0201: Attribute 'script_dir' defined outside __init__ (attribute-defined-outside-init)
setup.py:1:0: F5101: Django is not available on the PYTHONPATH (django-not-available)

-------------------------------------------------------------------
Your code has been rated at 5.00/10 (previous run: 10.00/10, -5.00)
```

## Actual Output
```
(venv3) emily.hontoria@EmilyHontoriaMBP app % pre-commit run pylint --files setup.py
pylint...................................................................Failed
- hook id: pylint
- exit code: 1

************* Module pylint_django
pylint_django:1:0: F5101: Django is not available on the PYTHONPATH (django-not-available)
Traceback (most recent call last):
  File "/Users/emily.hontoria/.cache/pre-commit/repopb5fa49c/py_env-python3.7/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/Users/emily.hontoria/.cache/pre-commit/repopb5fa49c/py_env-python3.7/lib/python3.7/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/Users/emily.hontoria/.cache/pre-commit/repopb5fa49c/py_env-python3.7/lib/python3.7/site-packages/pylint/lint/run.py", line 358, in __init__
    linter.check(args)
  File "/Users/emily.hontoria/.cache/pre-commit/repopb5fa49c/py_env-python3.7/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 877, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/Users/emily.hontoria/.cache/pre-commit/repopb5fa49c/py_env-python3.7/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 908, in _check_files
    with self._astroid_module_checker() as check_astroid_module:
  File "/Users/emily.hontoria/.pyenv/versions/3.7.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/emily.hontoria/.cache/pre-commit/repopb5fa49c/py_env-python3.7/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1017, in _astroid_module_checker
    checker.open()
  File "/Users/emily.hontoria/.cache/pre-commit/repopb5fa49c/py_env-python3.7/lib/python3.7/site-packages/pylint_django/checkers/foreign_key_strings.py", line 83, in open
    from django.core.exceptions import (  # pylint: disable=import-outside-toplevel
ModuleNotFoundError: No module named 'django'
```

**Comment by ehontoria** [comment]
I attempted to add `django` as a required package for the `pre-commit` configuration but then ended up with other module errors similar to the `django` one detailed above.

**Comment by atodorov** [comment]
From README:

> WARNING: pylint-django will not install Django by default because this causes more trouble than good, see discussion. If you wish to automatically install the latest version of Django then:
> 
> pip install pylint-django[with_django]
> 
> otherwise sort out your testing environment and please DO NOT report issues about missing Django!
>
