### ISSUE TITLE
Linter 'pylint' failed to parse the output when plugin loaded

### ISSUE THREAD

**Issue by Repsay** [PyCQA/pylint-django#384]
I have installed pylint_django and when running from the command line I am not receiving an error. But when run from vscode itself pylint crashes due to Syntax error 

**Versions**
pylint 2.15.5
astroid 2.12.12
Python 3.10.6 (main, Nov 2 2022, 18:53:38) [GCC 11.3.0]
pylint_django 2.5.3

**VSCODE**
Version: 1.73.1 (system setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

##########Linting Output - pylint##########

[ERROR 2022-10-30 19:15:36.361]: Linter 'pylint' failed to parse the output '. SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at s.parseMessages (/root/.vscode-server/extensions/ms-python.python-2022.18.2/src/client/linters/pylint.ts:48:39)
    at s.run (/root/.vscode-server/extensions/ms-python.python-2022.18.2/src/client/linters/baseLinter.ts:99:31)
    at runMicrotasks (<anonymous>)
    at process.messages (node:internal/process/task_queues:96:5)
    at s.runLinter (/root/.vscode-server/extensions/ms-python.python-2022.18.2/src/client/linters/pylint.ts:21:15)

**PIP FREEZE**
asgiref==3.5.2
astroid==2.12.12
black==22.10.0
certifi==2022.9.24
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.6
cssbeautifier==1.14.7
cssselect2==0.7.0
dill==0.3.6
dj-database-url==1.0.0
Django==3.1.14
django-classy-tags==3.0.1
django-cms==3.8.0
django-filer==2.2.3
django-formtools==2.4
django-js-asset==2.0.0
django-mptt==0.14.0
django-polymorphic==3.1.0
django-sekizai==3.0.1
django-treebeard==4.4
djangocms-admin-style==2.0.2
djangocms-attributes-field==2.1.0
djangocms-bootstrap4==2.0.0
djangocms-file==3.0.0
djangocms-googlemap==2.0.0
djangocms-icon==2.0.0
djangocms-installer==2.0.0
djangocms-link==3.1.0
djangocms-picture==3.0.0
djangocms-style==3.0.0
djangocms-text-ckeditor==4.0.0
djangocms-video==3.0.0
djangorestframework==3.14.0
djlint==1.19.4
easy-thumbnails==2.8.3
EditorConfig==0.12.3
free-proxy==1.0.6
gunicorn==20.1.0
html-tag-names==0.1.2
html-void-elements==0.1.0
html5lib==1.1
idna==3.4
importlib-metadata==5.0.0
isort==5.10.1
jellyfish==0.9.0
jsbeautifier==1.14.7
lazy-object-proxy==1.8.0
lxml==4.9.1
mccabe==0.7.0
mypy-extensions==0.4.3
pathspec==0.10.1
Pillow==9.3.0
platformdirs==2.5.2
psycopg2==2.9.5
pylint==2.15.5
pylint-django==2.5.3
pylint-plugin-utils==0.7
pytz==2022.6
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
regex==2022.10.31
reportlab==3.6.12
requests==2.28.1
six==1.16.0
sqlparse==0.4.3
supermarket-connector==0.0.26
svglib==1.4.1
tinycss2==1.2.1
tomli==2.0.1
tomlkit==0.11.6
tqdm==4.64.1
tzdata==2022.6
tzlocal==4.2
Unidecode==1.1.2
urllib3==1.26.12
webencodings==0.5.1
wrapt==1.14.1
zipp==3.10.0

**Comment by GaNiziolek** [comment]
same here
